### ISSUE TITLE
Cannot build under Ubuntu 23.10

### ISSUE THREAD

**Issue by andimik** [deeptho/media_build_old#2]
After years with TBS drivers under Ubuntu (which I have successfully used on various PCs) I've installed 23.10 in a new environment and cloned neumo latest drivers [369b3d2d](https://github.com/deeptho/linux_media)  and 2eabd09c from your repository.

But I cannot build it completely although the last line says I need to reboot. Could you write this line only when everything went fine?

I tried to follow the instructions in your readme.

[media_build_error.txt](https://github.com/deeptho/media_build/files/13418962/media_build_error.txt)

```
   33 | #define untagged_addr(addr)     ({                                      \
      | 
make[4]: *** [scripts/Makefile.build:251: /home/andreas/apps/media_build/v4l/ad5820.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [scripts/Makefile.build:251: /home/andreas/apps/media_build/v4l/max2175.o] Error 1
make[4]: *** [scripts/Makefile.build:251: /home/andreas/apps/media_build/v4l/adp1653.o] Error 1
make[4]: *** [scripts/Makefile.build:251: /home/andreas/apps/media_build/v4l/adv7170.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.5.0-9-generic/Makefile:2037: /home/andreas/apps/media_build/v4l] Error 2
make[2]: *** [Makefile:234: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.5.0-9-generic'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/home/andreas/apps/media_build/v4l'
make: *** [Makefile:26: all] Error 2
V4L drivers installation done
You need to reboot...

```

Can you advice me what I am doing wrong?

**Comment by deeptho** [comment]
Clearly it does not compile, so you will have to fix that. Perhaps you are using a non supported kernel,
or perhaps you made an error somewhere.

**Comment by andimik** [comment]
Which Ubuntu Version can you or your users recommend?

**Comment by deeptho** [comment]
I don't use ubuntu myself. Why would the ubuntu version be relevant? What matters is the kernel version and
using media_build correctly (not always easy) and using a supported kernel version. I cannot test them all.
6.3.8 should work.

**Comment by deeptho** [comment]
You can try the latest version. I managed to compile it under ubuntu 23

**Comment by andimik** [comment]
Well, compiling was successful (thanks), but after the reboot I have freezes due to ACPI.

I need to try some other `grub2` boot options.

`acpi=off` and `noapic` did not help.

**Comment by andimik** [comment]
Well, I gave up. I'm sorry for the wasted time. So you recommend to use fedora for your drivers?

I'm back now to TBS drivers, which do work for all transponders without any problems and do not need any hacks in `grub2`. 

With your driver it was very very difficult to tune with lots of errors. After a while I had to reboot anyway.

Maybe you can sync with the TBS drivers and provide a patch file with your changings?

**Comment by deeptho** [comment]
The drivers are fully synced with tbs. And if you experience problems with grub and acpi then that is certainly unrelated to the blindscan drivers.

**Comment by andimik** [comment]
I've installed Fedora 39, but your drivers cannot be successfully build ...

> if you experience problems with grub and acpi then that is certainly unrelated to the blindscan drivers.

I don't think so. When I installed the TBS drivers, then I had no issue with acpi.

**Comment by deeptho** [comment]
I have installed the drivers on fedora39 myself. They work. 

If you think there is a problem, then you will need to provide some evidence that can actually be used to 
check that it is real and can shed some light on how to fix it. In that case reopen the ticket.

I am not a magician. I cannot fix problems that I cannot reproduce and I cannot guess what is specific about your 
setup or perhaps about how you installed the drivers.

**Comment by andimik** [comment]
I think I found the root cause in your `install.sh` script. In my case I had renamed the `media` directory to `deep_media`.

Although I have declared the directory in the `make dir` line to `make dir DIR=../deep_media`

But then the `install.sh` overwrites this value and building will fail, because the folder doesn't exist.

So please remove the lines from the script as your `Readme.md` already mention them.

**Comment by deeptho** [comment]
So in other words: you did not follow the instructions.
That is fine, but then you have to fix the problems yourself.
